const DEFAULT_ENV = 'local';
const DEFAULT_PORT_NUMBER = 8000;
const DEFAULT_DOMAIN = 'http://localhost:8000';
const DEFAULT_API_PREFIX = '/api';
const DEFAULT_ACCESS_ALLOWED_ORIGIN = 'http://localhost:3001';

export const SETTING = {
  ENV: process.env.NODE_ENV ?? DEFAULT_ENV,
  PORT_NUMBER: process.env.PORT_NUMBER ?? DEFAULT_PORT_NUMBER,
  DOMAIN: process.env.DOMAIN ?? DEFAULT_DOMAIN,
  API_PREFIX: process.env.API_PREFIX ?? DEFAULT_API_PREFIX,
  ACCESS_ALLOWED_ORIGIN: process.env.ACCESS_ALLOWED_ORIGIN ?? DEFAULT_ACCESS_ALLOWED_ORIGIN,
} as const;
